### ISSUE TITLE
Incorrect background below 480px width

### ISSUE THREAD

**Issue by csvn** [auth0/lock-theme-gradient#1]
Hi,

![image](https://cloud.githubusercontent.com/assets/8770194/11558872/64df5256-99b5-11e5-93a4-085993624b4b.png)

The right image I corrected by turning off the below styles. It's caused due to higher selector specificity on `.a0-overlay` and `.a0-panel`:

``` css
#a0-lock.a0-theme-default .a0-popup .a0-overlay {
    ...
    background: #fff;
}

#a0-lock.a0-theme-default .a0-popup .a0-centrix .a0-panel {
    ...
    background: #fff;
}
```
